server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url : jdbc:mysql://10.179.210.105:3306/semantics?useUnicode=true&useSSL=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true
    username : root
    password : '123123'
    driver-class-name: com.mysql.jdbc.Driver
