/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lsy.knowledge.traffic.base.domain.thrift;


public enum CoordinateType implements org.apache.thrift.TEnum {
  BD_09(1),
  GCJ_02(2),
  WGS_84(4);

  private final int value;

  private CoordinateType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CoordinateType findByValue(int value) { 
    switch (value) {
      case 1:
        return BD_09;
      case 2:
        return GCJ_02;
      case 4:
        return WGS_84;
      default:
        return null;
    }
  }
}
