/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lsy.knowledge.traffic.base.domain.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-01-03")
public class MapMatchPointList implements org.apache.thrift.TBase<MapMatchPointList, MapMatchPointList._Fields>, java.io.Serializable, Cloneable, Comparable<MapMatchPointList> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MapMatchPointList");

  private static final org.apache.thrift.protocol.TField MAP_MATCH_POINT_VEC_FIELD_DESC = new org.apache.thrift.protocol.TField("map_match_point_vec", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MapMatchPointListStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MapMatchPointListTupleSchemeFactory();

  public java.util.List<map_match_point_t> map_match_point_vec; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MAP_MATCH_POINT_VEC((short)1, "map_match_point_vec");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MAP_MATCH_POINT_VEC
          return MAP_MATCH_POINT_VEC;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MAP_MATCH_POINT_VEC, new org.apache.thrift.meta_data.FieldMetaData("map_match_point_vec", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, map_match_point_t.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MapMatchPointList.class, metaDataMap);
  }

  public MapMatchPointList() {
  }

  public MapMatchPointList(
    java.util.List<map_match_point_t> map_match_point_vec)
  {
    this();
    this.map_match_point_vec = map_match_point_vec;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MapMatchPointList(MapMatchPointList other) {
    if (other.isSetMap_match_point_vec()) {
      java.util.List<map_match_point_t> __this__map_match_point_vec = new java.util.ArrayList<map_match_point_t>(other.map_match_point_vec.size());
      for (map_match_point_t other_element : other.map_match_point_vec) {
        __this__map_match_point_vec.add(new map_match_point_t(other_element));
      }
      this.map_match_point_vec = __this__map_match_point_vec;
    }
  }

  public MapMatchPointList deepCopy() {
    return new MapMatchPointList(this);
  }

  @Override
  public void clear() {
    this.map_match_point_vec = null;
  }

  public int getMap_match_point_vecSize() {
    return (this.map_match_point_vec == null) ? 0 : this.map_match_point_vec.size();
  }

  public java.util.Iterator<map_match_point_t> getMap_match_point_vecIterator() {
    return (this.map_match_point_vec == null) ? null : this.map_match_point_vec.iterator();
  }

  public void addToMap_match_point_vec(map_match_point_t elem) {
    if (this.map_match_point_vec == null) {
      this.map_match_point_vec = new java.util.ArrayList<map_match_point_t>();
    }
    this.map_match_point_vec.add(elem);
  }

  public java.util.List<map_match_point_t> getMap_match_point_vec() {
    return this.map_match_point_vec;
  }

  public MapMatchPointList setMap_match_point_vec(java.util.List<map_match_point_t> map_match_point_vec) {
    this.map_match_point_vec = map_match_point_vec;
    return this;
  }

  public void unsetMap_match_point_vec() {
    this.map_match_point_vec = null;
  }

  /** Returns true if field map_match_point_vec is set (has been assigned a value) and false otherwise */
  public boolean isSetMap_match_point_vec() {
    return this.map_match_point_vec != null;
  }

  public void setMap_match_point_vecIsSet(boolean value) {
    if (!value) {
      this.map_match_point_vec = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case MAP_MATCH_POINT_VEC:
      if (value == null) {
        unsetMap_match_point_vec();
      } else {
        setMap_match_point_vec((java.util.List<map_match_point_t>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MAP_MATCH_POINT_VEC:
      return getMap_match_point_vec();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MAP_MATCH_POINT_VEC:
      return isSetMap_match_point_vec();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof MapMatchPointList)
      return this.equals((MapMatchPointList)that);
    return false;
  }

  public boolean equals(MapMatchPointList that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_map_match_point_vec = true && this.isSetMap_match_point_vec();
    boolean that_present_map_match_point_vec = true && that.isSetMap_match_point_vec();
    if (this_present_map_match_point_vec || that_present_map_match_point_vec) {
      if (!(this_present_map_match_point_vec && that_present_map_match_point_vec))
        return false;
      if (!this.map_match_point_vec.equals(that.map_match_point_vec))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMap_match_point_vec()) ? 131071 : 524287);
    if (isSetMap_match_point_vec())
      hashCode = hashCode * 8191 + map_match_point_vec.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(MapMatchPointList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetMap_match_point_vec()).compareTo(other.isSetMap_match_point_vec());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMap_match_point_vec()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.map_match_point_vec, other.map_match_point_vec);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("MapMatchPointList(");
    boolean first = true;

    sb.append("map_match_point_vec:");
    if (this.map_match_point_vec == null) {
      sb.append("null");
    } else {
      sb.append(this.map_match_point_vec);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MapMatchPointListStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MapMatchPointListStandardScheme getScheme() {
      return new MapMatchPointListStandardScheme();
    }
  }

  private static class MapMatchPointListStandardScheme extends org.apache.thrift.scheme.StandardScheme<MapMatchPointList> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MapMatchPointList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MAP_MATCH_POINT_VEC
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.map_match_point_vec = new java.util.ArrayList<map_match_point_t>(_list8.size);
                map_match_point_t _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new map_match_point_t();
                  _elem9.read(iprot);
                  struct.map_match_point_vec.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setMap_match_point_vecIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MapMatchPointList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.map_match_point_vec != null) {
        oprot.writeFieldBegin(MAP_MATCH_POINT_VEC_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.map_match_point_vec.size()));
          for (map_match_point_t _iter11 : struct.map_match_point_vec)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MapMatchPointListTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MapMatchPointListTupleScheme getScheme() {
      return new MapMatchPointListTupleScheme();
    }
  }

  private static class MapMatchPointListTupleScheme extends org.apache.thrift.scheme.TupleScheme<MapMatchPointList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MapMatchPointList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMap_match_point_vec()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMap_match_point_vec()) {
        {
          oprot.writeI32(struct.map_match_point_vec.size());
          for (map_match_point_t _iter12 : struct.map_match_point_vec)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MapMatchPointList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.map_match_point_vec = new java.util.ArrayList<map_match_point_t>(_list13.size);
          map_match_point_t _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new map_match_point_t();
            _elem14.read(iprot);
            struct.map_match_point_vec.add(_elem14);
          }
        }
        struct.setMap_match_point_vecIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

