/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lsy.knowledge.traffic.base.domain.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2017-12-27")
public class PointTraj2DistResponse implements org.apache.thrift.TBase<PointTraj2DistResponse, PointTraj2DistResponse._Fields>, java.io.Serializable, Cloneable, Comparable<PointTraj2DistResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PointTraj2DistResponse");

  private static final org.apache.thrift.protocol.TField RET_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("ret_code", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField RET_MSG_FIELD_DESC = new org.apache.thrift.protocol.TField("ret_msg", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DIST_VEC_FIELD_DESC = new org.apache.thrift.protocol.TField("dist_vec", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PointTraj2DistResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PointTraj2DistResponseTupleSchemeFactory();

  public int ret_code; // required
  public java.lang.String ret_msg; // required
  public java.util.List<traj_dist_t> dist_vec; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RET_CODE((short)1, "ret_code"),
    RET_MSG((short)2, "ret_msg"),
    DIST_VEC((short)3, "dist_vec");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RET_CODE
          return RET_CODE;
        case 2: // RET_MSG
          return RET_MSG;
        case 3: // DIST_VEC
          return DIST_VEC;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RET_CODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RET_CODE, new org.apache.thrift.meta_data.FieldMetaData("ret_code", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.RET_MSG, new org.apache.thrift.meta_data.FieldMetaData("ret_msg", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DIST_VEC, new org.apache.thrift.meta_data.FieldMetaData("dist_vec", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, traj_dist_t.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PointTraj2DistResponse.class, metaDataMap);
  }

  public PointTraj2DistResponse() {
  }

  public PointTraj2DistResponse(
    int ret_code,
    java.lang.String ret_msg,
    java.util.List<traj_dist_t> dist_vec)
  {
    this();
    this.ret_code = ret_code;
    setRet_codeIsSet(true);
    this.ret_msg = ret_msg;
    this.dist_vec = dist_vec;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PointTraj2DistResponse(PointTraj2DistResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.ret_code = other.ret_code;
    if (other.isSetRet_msg()) {
      this.ret_msg = other.ret_msg;
    }
    if (other.isSetDist_vec()) {
      java.util.List<traj_dist_t> __this__dist_vec = new java.util.ArrayList<traj_dist_t>(other.dist_vec.size());
      for (traj_dist_t other_element : other.dist_vec) {
        __this__dist_vec.add(new traj_dist_t(other_element));
      }
      this.dist_vec = __this__dist_vec;
    }
  }

  public PointTraj2DistResponse deepCopy() {
    return new PointTraj2DistResponse(this);
  }

  @Override
  public void clear() {
    setRet_codeIsSet(false);
    this.ret_code = 0;
    this.ret_msg = null;
    this.dist_vec = null;
  }

  public int getRet_code() {
    return this.ret_code;
  }

  public PointTraj2DistResponse setRet_code(int ret_code) {
    this.ret_code = ret_code;
    setRet_codeIsSet(true);
    return this;
  }

  public void unsetRet_code() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RET_CODE_ISSET_ID);
  }

  /** Returns true if field ret_code is set (has been assigned a value) and false otherwise */
  public boolean isSetRet_code() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RET_CODE_ISSET_ID);
  }

  public void setRet_codeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RET_CODE_ISSET_ID, value);
  }

  public java.lang.String getRet_msg() {
    return this.ret_msg;
  }

  public PointTraj2DistResponse setRet_msg(java.lang.String ret_msg) {
    this.ret_msg = ret_msg;
    return this;
  }

  public void unsetRet_msg() {
    this.ret_msg = null;
  }

  /** Returns true if field ret_msg is set (has been assigned a value) and false otherwise */
  public boolean isSetRet_msg() {
    return this.ret_msg != null;
  }

  public void setRet_msgIsSet(boolean value) {
    if (!value) {
      this.ret_msg = null;
    }
  }

  public int getDist_vecSize() {
    return (this.dist_vec == null) ? 0 : this.dist_vec.size();
  }

  public java.util.Iterator<traj_dist_t> getDist_vecIterator() {
    return (this.dist_vec == null) ? null : this.dist_vec.iterator();
  }

  public void addToDist_vec(traj_dist_t elem) {
    if (this.dist_vec == null) {
      this.dist_vec = new java.util.ArrayList<traj_dist_t>();
    }
    this.dist_vec.add(elem);
  }

  public java.util.List<traj_dist_t> getDist_vec() {
    return this.dist_vec;
  }

  public PointTraj2DistResponse setDist_vec(java.util.List<traj_dist_t> dist_vec) {
    this.dist_vec = dist_vec;
    return this;
  }

  public void unsetDist_vec() {
    this.dist_vec = null;
  }

  /** Returns true if field dist_vec is set (has been assigned a value) and false otherwise */
  public boolean isSetDist_vec() {
    return this.dist_vec != null;
  }

  public void setDist_vecIsSet(boolean value) {
    if (!value) {
      this.dist_vec = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case RET_CODE:
      if (value == null) {
        unsetRet_code();
      } else {
        setRet_code((java.lang.Integer)value);
      }
      break;

    case RET_MSG:
      if (value == null) {
        unsetRet_msg();
      } else {
        setRet_msg((java.lang.String)value);
      }
      break;

    case DIST_VEC:
      if (value == null) {
        unsetDist_vec();
      } else {
        setDist_vec((java.util.List<traj_dist_t>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case RET_CODE:
      return getRet_code();

    case RET_MSG:
      return getRet_msg();

    case DIST_VEC:
      return getDist_vec();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case RET_CODE:
      return isSetRet_code();
    case RET_MSG:
      return isSetRet_msg();
    case DIST_VEC:
      return isSetDist_vec();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof PointTraj2DistResponse)
      return this.equals((PointTraj2DistResponse)that);
    return false;
  }

  public boolean equals(PointTraj2DistResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_ret_code = true;
    boolean that_present_ret_code = true;
    if (this_present_ret_code || that_present_ret_code) {
      if (!(this_present_ret_code && that_present_ret_code))
        return false;
      if (this.ret_code != that.ret_code)
        return false;
    }

    boolean this_present_ret_msg = true && this.isSetRet_msg();
    boolean that_present_ret_msg = true && that.isSetRet_msg();
    if (this_present_ret_msg || that_present_ret_msg) {
      if (!(this_present_ret_msg && that_present_ret_msg))
        return false;
      if (!this.ret_msg.equals(that.ret_msg))
        return false;
    }

    boolean this_present_dist_vec = true && this.isSetDist_vec();
    boolean that_present_dist_vec = true && that.isSetDist_vec();
    if (this_present_dist_vec || that_present_dist_vec) {
      if (!(this_present_dist_vec && that_present_dist_vec))
        return false;
      if (!this.dist_vec.equals(that.dist_vec))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ret_code;

    hashCode = hashCode * 8191 + ((isSetRet_msg()) ? 131071 : 524287);
    if (isSetRet_msg())
      hashCode = hashCode * 8191 + ret_msg.hashCode();

    hashCode = hashCode * 8191 + ((isSetDist_vec()) ? 131071 : 524287);
    if (isSetDist_vec())
      hashCode = hashCode * 8191 + dist_vec.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(PointTraj2DistResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetRet_code()).compareTo(other.isSetRet_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRet_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ret_code, other.ret_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRet_msg()).compareTo(other.isSetRet_msg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRet_msg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ret_msg, other.ret_msg);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDist_vec()).compareTo(other.isSetDist_vec());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDist_vec()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dist_vec, other.dist_vec);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PointTraj2DistResponse(");
    boolean first = true;

    sb.append("ret_code:");
    sb.append(this.ret_code);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ret_msg:");
    if (this.ret_msg == null) {
      sb.append("null");
    } else {
      sb.append(this.ret_msg);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dist_vec:");
    if (this.dist_vec == null) {
      sb.append("null");
    } else {
      sb.append(this.dist_vec);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PointTraj2DistResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PointTraj2DistResponseStandardScheme getScheme() {
      return new PointTraj2DistResponseStandardScheme();
    }
  }

  private static class PointTraj2DistResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<PointTraj2DistResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PointTraj2DistResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RET_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ret_code = iprot.readI32();
              struct.setRet_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RET_MSG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ret_msg = iprot.readString();
              struct.setRet_msgIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DIST_VEC
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list48 = iprot.readListBegin();
                struct.dist_vec = new java.util.ArrayList<traj_dist_t>(_list48.size);
                traj_dist_t _elem49;
                for (int _i50 = 0; _i50 < _list48.size; ++_i50)
                {
                  _elem49 = new traj_dist_t();
                  _elem49.read(iprot);
                  struct.dist_vec.add(_elem49);
                }
                iprot.readListEnd();
              }
              struct.setDist_vecIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PointTraj2DistResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(RET_CODE_FIELD_DESC);
      oprot.writeI32(struct.ret_code);
      oprot.writeFieldEnd();
      if (struct.ret_msg != null) {
        oprot.writeFieldBegin(RET_MSG_FIELD_DESC);
        oprot.writeString(struct.ret_msg);
        oprot.writeFieldEnd();
      }
      if (struct.dist_vec != null) {
        oprot.writeFieldBegin(DIST_VEC_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.dist_vec.size()));
          for (traj_dist_t _iter51 : struct.dist_vec)
          {
            _iter51.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PointTraj2DistResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PointTraj2DistResponseTupleScheme getScheme() {
      return new PointTraj2DistResponseTupleScheme();
    }
  }

  private static class PointTraj2DistResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<PointTraj2DistResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PointTraj2DistResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetRet_code()) {
        optionals.set(0);
      }
      if (struct.isSetRet_msg()) {
        optionals.set(1);
      }
      if (struct.isSetDist_vec()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetRet_code()) {
        oprot.writeI32(struct.ret_code);
      }
      if (struct.isSetRet_msg()) {
        oprot.writeString(struct.ret_msg);
      }
      if (struct.isSetDist_vec()) {
        {
          oprot.writeI32(struct.dist_vec.size());
          for (traj_dist_t _iter52 : struct.dist_vec)
          {
            _iter52.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PointTraj2DistResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.ret_code = iprot.readI32();
        struct.setRet_codeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ret_msg = iprot.readString();
        struct.setRet_msgIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list53 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.dist_vec = new java.util.ArrayList<traj_dist_t>(_list53.size);
          traj_dist_t _elem54;
          for (int _i55 = 0; _i55 < _list53.size; ++_i55)
          {
            _elem54 = new traj_dist_t();
            _elem54.read(iprot);
            struct.dist_vec.add(_elem54);
          }
        }
        struct.setDist_vecIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

