/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lsy.knowledge.traffic.base.domain.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2017-12-27")
public class ServerKeepAliveResponse implements org.apache.thrift.TBase<ServerKeepAliveResponse, ServerKeepAliveResponse._Fields>, java.io.Serializable, Cloneable, Comparable<ServerKeepAliveResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ServerKeepAliveResponse");

  private static final org.apache.thrift.protocol.TField RET_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("ret_code", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField RET_MSG_FIELD_DESC = new org.apache.thrift.protocol.TField("ret_msg", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ServerKeepAliveResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ServerKeepAliveResponseTupleSchemeFactory();

  public int ret_code; // required
  public java.lang.String ret_msg; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RET_CODE((short)1, "ret_code"),
    RET_MSG((short)2, "ret_msg");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RET_CODE
          return RET_CODE;
        case 2: // RET_MSG
          return RET_MSG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RET_CODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RET_CODE, new org.apache.thrift.meta_data.FieldMetaData("ret_code", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.RET_MSG, new org.apache.thrift.meta_data.FieldMetaData("ret_msg", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ServerKeepAliveResponse.class, metaDataMap);
  }

  public ServerKeepAliveResponse() {
  }

  public ServerKeepAliveResponse(
    int ret_code,
    java.lang.String ret_msg)
  {
    this();
    this.ret_code = ret_code;
    setRet_codeIsSet(true);
    this.ret_msg = ret_msg;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ServerKeepAliveResponse(ServerKeepAliveResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.ret_code = other.ret_code;
    if (other.isSetRet_msg()) {
      this.ret_msg = other.ret_msg;
    }
  }

  public ServerKeepAliveResponse deepCopy() {
    return new ServerKeepAliveResponse(this);
  }

  @Override
  public void clear() {
    setRet_codeIsSet(false);
    this.ret_code = 0;
    this.ret_msg = null;
  }

  public int getRet_code() {
    return this.ret_code;
  }

  public ServerKeepAliveResponse setRet_code(int ret_code) {
    this.ret_code = ret_code;
    setRet_codeIsSet(true);
    return this;
  }

  public void unsetRet_code() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RET_CODE_ISSET_ID);
  }

  /** Returns true if field ret_code is set (has been assigned a value) and false otherwise */
  public boolean isSetRet_code() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RET_CODE_ISSET_ID);
  }

  public void setRet_codeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RET_CODE_ISSET_ID, value);
  }

  public java.lang.String getRet_msg() {
    return this.ret_msg;
  }

  public ServerKeepAliveResponse setRet_msg(java.lang.String ret_msg) {
    this.ret_msg = ret_msg;
    return this;
  }

  public void unsetRet_msg() {
    this.ret_msg = null;
  }

  /** Returns true if field ret_msg is set (has been assigned a value) and false otherwise */
  public boolean isSetRet_msg() {
    return this.ret_msg != null;
  }

  public void setRet_msgIsSet(boolean value) {
    if (!value) {
      this.ret_msg = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case RET_CODE:
      if (value == null) {
        unsetRet_code();
      } else {
        setRet_code((java.lang.Integer)value);
      }
      break;

    case RET_MSG:
      if (value == null) {
        unsetRet_msg();
      } else {
        setRet_msg((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case RET_CODE:
      return getRet_code();

    case RET_MSG:
      return getRet_msg();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case RET_CODE:
      return isSetRet_code();
    case RET_MSG:
      return isSetRet_msg();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ServerKeepAliveResponse)
      return this.equals((ServerKeepAliveResponse)that);
    return false;
  }

  public boolean equals(ServerKeepAliveResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_ret_code = true;
    boolean that_present_ret_code = true;
    if (this_present_ret_code || that_present_ret_code) {
      if (!(this_present_ret_code && that_present_ret_code))
        return false;
      if (this.ret_code != that.ret_code)
        return false;
    }

    boolean this_present_ret_msg = true && this.isSetRet_msg();
    boolean that_present_ret_msg = true && that.isSetRet_msg();
    if (this_present_ret_msg || that_present_ret_msg) {
      if (!(this_present_ret_msg && that_present_ret_msg))
        return false;
      if (!this.ret_msg.equals(that.ret_msg))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ret_code;

    hashCode = hashCode * 8191 + ((isSetRet_msg()) ? 131071 : 524287);
    if (isSetRet_msg())
      hashCode = hashCode * 8191 + ret_msg.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ServerKeepAliveResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetRet_code()).compareTo(other.isSetRet_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRet_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ret_code, other.ret_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRet_msg()).compareTo(other.isSetRet_msg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRet_msg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ret_msg, other.ret_msg);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ServerKeepAliveResponse(");
    boolean first = true;

    sb.append("ret_code:");
    sb.append(this.ret_code);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ret_msg:");
    if (this.ret_msg == null) {
      sb.append("null");
    } else {
      sb.append(this.ret_msg);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ServerKeepAliveResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ServerKeepAliveResponseStandardScheme getScheme() {
      return new ServerKeepAliveResponseStandardScheme();
    }
  }

  private static class ServerKeepAliveResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<ServerKeepAliveResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ServerKeepAliveResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RET_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ret_code = iprot.readI32();
              struct.setRet_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RET_MSG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ret_msg = iprot.readString();
              struct.setRet_msgIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ServerKeepAliveResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(RET_CODE_FIELD_DESC);
      oprot.writeI32(struct.ret_code);
      oprot.writeFieldEnd();
      if (struct.ret_msg != null) {
        oprot.writeFieldBegin(RET_MSG_FIELD_DESC);
        oprot.writeString(struct.ret_msg);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ServerKeepAliveResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ServerKeepAliveResponseTupleScheme getScheme() {
      return new ServerKeepAliveResponseTupleScheme();
    }
  }

  private static class ServerKeepAliveResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<ServerKeepAliveResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ServerKeepAliveResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetRet_code()) {
        optionals.set(0);
      }
      if (struct.isSetRet_msg()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetRet_code()) {
        oprot.writeI32(struct.ret_code);
      }
      if (struct.isSetRet_msg()) {
        oprot.writeString(struct.ret_msg);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ServerKeepAliveResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.ret_code = iprot.readI32();
        struct.setRet_codeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ret_msg = iprot.readString();
        struct.setRet_msgIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

