/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lsy.knowledge.traffic.base.domain.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2017-12-27")
public class Trace implements org.apache.thrift.TBase<Trace, Trace._Fields>, java.io.Serializable, Cloneable, Comparable<Trace> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Trace");

  private static final org.apache.thrift.protocol.TField LOG_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("logId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CALLER_FIELD_DESC = new org.apache.thrift.protocol.TField("caller", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField SPAN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("spanId", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField SRC_METHOD_FIELD_DESC = new org.apache.thrift.protocol.TField("srcMethod", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField HINT_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("hintCode", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField HINT_CONTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("hintContent", org.apache.thrift.protocol.TType.STRING, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TraceStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TraceTupleSchemeFactory();

  public java.lang.String logId; // required
  public java.lang.String caller; // required
  public java.lang.String spanId; // optional
  public java.lang.String srcMethod; // optional
  public long hintCode; // optional
  public java.lang.String hintContent; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LOG_ID((short)1, "logId"),
    CALLER((short)2, "caller"),
    SPAN_ID((short)3, "spanId"),
    SRC_METHOD((short)4, "srcMethod"),
    HINT_CODE((short)5, "hintCode"),
    HINT_CONTENT((short)6, "hintContent");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LOG_ID
          return LOG_ID;
        case 2: // CALLER
          return CALLER;
        case 3: // SPAN_ID
          return SPAN_ID;
        case 4: // SRC_METHOD
          return SRC_METHOD;
        case 5: // HINT_CODE
          return HINT_CODE;
        case 6: // HINT_CONTENT
          return HINT_CONTENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HINTCODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.SPAN_ID, _Fields.SRC_METHOD, _Fields.HINT_CODE, _Fields.HINT_CONTENT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LOG_ID, new org.apache.thrift.meta_data.FieldMetaData("logId", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CALLER, new org.apache.thrift.meta_data.FieldMetaData("caller", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SPAN_ID, new org.apache.thrift.meta_data.FieldMetaData("spanId", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SRC_METHOD, new org.apache.thrift.meta_data.FieldMetaData("srcMethod", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HINT_CODE, new org.apache.thrift.meta_data.FieldMetaData("hintCode", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.HINT_CONTENT, new org.apache.thrift.meta_data.FieldMetaData("hintContent", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Trace.class, metaDataMap);
  }

  public Trace() {
  }

  public Trace(
    java.lang.String logId,
    java.lang.String caller)
  {
    this();
    this.logId = logId;
    this.caller = caller;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Trace(Trace other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetLogId()) {
      this.logId = other.logId;
    }
    if (other.isSetCaller()) {
      this.caller = other.caller;
    }
    if (other.isSetSpanId()) {
      this.spanId = other.spanId;
    }
    if (other.isSetSrcMethod()) {
      this.srcMethod = other.srcMethod;
    }
    this.hintCode = other.hintCode;
    if (other.isSetHintContent()) {
      this.hintContent = other.hintContent;
    }
  }

  public Trace deepCopy() {
    return new Trace(this);
  }

  @Override
  public void clear() {
    this.logId = null;
    this.caller = null;
    this.spanId = null;
    this.srcMethod = null;
    setHintCodeIsSet(false);
    this.hintCode = 0;
    this.hintContent = null;
  }

  public java.lang.String getLogId() {
    return this.logId;
  }

  public Trace setLogId(java.lang.String logId) {
    this.logId = logId;
    return this;
  }

  public void unsetLogId() {
    this.logId = null;
  }

  /** Returns true if field logId is set (has been assigned a value) and false otherwise */
  public boolean isSetLogId() {
    return this.logId != null;
  }

  public void setLogIdIsSet(boolean value) {
    if (!value) {
      this.logId = null;
    }
  }

  public java.lang.String getCaller() {
    return this.caller;
  }

  public Trace setCaller(java.lang.String caller) {
    this.caller = caller;
    return this;
  }

  public void unsetCaller() {
    this.caller = null;
  }

  /** Returns true if field caller is set (has been assigned a value) and false otherwise */
  public boolean isSetCaller() {
    return this.caller != null;
  }

  public void setCallerIsSet(boolean value) {
    if (!value) {
      this.caller = null;
    }
  }

  public java.lang.String getSpanId() {
    return this.spanId;
  }

  public Trace setSpanId(java.lang.String spanId) {
    this.spanId = spanId;
    return this;
  }

  public void unsetSpanId() {
    this.spanId = null;
  }

  /** Returns true if field spanId is set (has been assigned a value) and false otherwise */
  public boolean isSetSpanId() {
    return this.spanId != null;
  }

  public void setSpanIdIsSet(boolean value) {
    if (!value) {
      this.spanId = null;
    }
  }

  public java.lang.String getSrcMethod() {
    return this.srcMethod;
  }

  public Trace setSrcMethod(java.lang.String srcMethod) {
    this.srcMethod = srcMethod;
    return this;
  }

  public void unsetSrcMethod() {
    this.srcMethod = null;
  }

  /** Returns true if field srcMethod is set (has been assigned a value) and false otherwise */
  public boolean isSetSrcMethod() {
    return this.srcMethod != null;
  }

  public void setSrcMethodIsSet(boolean value) {
    if (!value) {
      this.srcMethod = null;
    }
  }

  public long getHintCode() {
    return this.hintCode;
  }

  public Trace setHintCode(long hintCode) {
    this.hintCode = hintCode;
    setHintCodeIsSet(true);
    return this;
  }

  public void unsetHintCode() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __HINTCODE_ISSET_ID);
  }

  /** Returns true if field hintCode is set (has been assigned a value) and false otherwise */
  public boolean isSetHintCode() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __HINTCODE_ISSET_ID);
  }

  public void setHintCodeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __HINTCODE_ISSET_ID, value);
  }

  public java.lang.String getHintContent() {
    return this.hintContent;
  }

  public Trace setHintContent(java.lang.String hintContent) {
    this.hintContent = hintContent;
    return this;
  }

  public void unsetHintContent() {
    this.hintContent = null;
  }

  /** Returns true if field hintContent is set (has been assigned a value) and false otherwise */
  public boolean isSetHintContent() {
    return this.hintContent != null;
  }

  public void setHintContentIsSet(boolean value) {
    if (!value) {
      this.hintContent = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case LOG_ID:
      if (value == null) {
        unsetLogId();
      } else {
        setLogId((java.lang.String)value);
      }
      break;

    case CALLER:
      if (value == null) {
        unsetCaller();
      } else {
        setCaller((java.lang.String)value);
      }
      break;

    case SPAN_ID:
      if (value == null) {
        unsetSpanId();
      } else {
        setSpanId((java.lang.String)value);
      }
      break;

    case SRC_METHOD:
      if (value == null) {
        unsetSrcMethod();
      } else {
        setSrcMethod((java.lang.String)value);
      }
      break;

    case HINT_CODE:
      if (value == null) {
        unsetHintCode();
      } else {
        setHintCode((java.lang.Long)value);
      }
      break;

    case HINT_CONTENT:
      if (value == null) {
        unsetHintContent();
      } else {
        setHintContent((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LOG_ID:
      return getLogId();

    case CALLER:
      return getCaller();

    case SPAN_ID:
      return getSpanId();

    case SRC_METHOD:
      return getSrcMethod();

    case HINT_CODE:
      return getHintCode();

    case HINT_CONTENT:
      return getHintContent();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LOG_ID:
      return isSetLogId();
    case CALLER:
      return isSetCaller();
    case SPAN_ID:
      return isSetSpanId();
    case SRC_METHOD:
      return isSetSrcMethod();
    case HINT_CODE:
      return isSetHintCode();
    case HINT_CONTENT:
      return isSetHintContent();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Trace)
      return this.equals((Trace)that);
    return false;
  }

  public boolean equals(Trace that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_logId = true && this.isSetLogId();
    boolean that_present_logId = true && that.isSetLogId();
    if (this_present_logId || that_present_logId) {
      if (!(this_present_logId && that_present_logId))
        return false;
      if (!this.logId.equals(that.logId))
        return false;
    }

    boolean this_present_caller = true && this.isSetCaller();
    boolean that_present_caller = true && that.isSetCaller();
    if (this_present_caller || that_present_caller) {
      if (!(this_present_caller && that_present_caller))
        return false;
      if (!this.caller.equals(that.caller))
        return false;
    }

    boolean this_present_spanId = true && this.isSetSpanId();
    boolean that_present_spanId = true && that.isSetSpanId();
    if (this_present_spanId || that_present_spanId) {
      if (!(this_present_spanId && that_present_spanId))
        return false;
      if (!this.spanId.equals(that.spanId))
        return false;
    }

    boolean this_present_srcMethod = true && this.isSetSrcMethod();
    boolean that_present_srcMethod = true && that.isSetSrcMethod();
    if (this_present_srcMethod || that_present_srcMethod) {
      if (!(this_present_srcMethod && that_present_srcMethod))
        return false;
      if (!this.srcMethod.equals(that.srcMethod))
        return false;
    }

    boolean this_present_hintCode = true && this.isSetHintCode();
    boolean that_present_hintCode = true && that.isSetHintCode();
    if (this_present_hintCode || that_present_hintCode) {
      if (!(this_present_hintCode && that_present_hintCode))
        return false;
      if (this.hintCode != that.hintCode)
        return false;
    }

    boolean this_present_hintContent = true && this.isSetHintContent();
    boolean that_present_hintContent = true && that.isSetHintContent();
    if (this_present_hintContent || that_present_hintContent) {
      if (!(this_present_hintContent && that_present_hintContent))
        return false;
      if (!this.hintContent.equals(that.hintContent))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetLogId()) ? 131071 : 524287);
    if (isSetLogId())
      hashCode = hashCode * 8191 + logId.hashCode();

    hashCode = hashCode * 8191 + ((isSetCaller()) ? 131071 : 524287);
    if (isSetCaller())
      hashCode = hashCode * 8191 + caller.hashCode();

    hashCode = hashCode * 8191 + ((isSetSpanId()) ? 131071 : 524287);
    if (isSetSpanId())
      hashCode = hashCode * 8191 + spanId.hashCode();

    hashCode = hashCode * 8191 + ((isSetSrcMethod()) ? 131071 : 524287);
    if (isSetSrcMethod())
      hashCode = hashCode * 8191 + srcMethod.hashCode();

    hashCode = hashCode * 8191 + ((isSetHintCode()) ? 131071 : 524287);
    if (isSetHintCode())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(hintCode);

    hashCode = hashCode * 8191 + ((isSetHintContent()) ? 131071 : 524287);
    if (isSetHintContent())
      hashCode = hashCode * 8191 + hintContent.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Trace other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetLogId()).compareTo(other.isSetLogId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLogId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.logId, other.logId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCaller()).compareTo(other.isSetCaller());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCaller()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.caller, other.caller);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSpanId()).compareTo(other.isSetSpanId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSpanId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.spanId, other.spanId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSrcMethod()).compareTo(other.isSetSrcMethod());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSrcMethod()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.srcMethod, other.srcMethod);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetHintCode()).compareTo(other.isSetHintCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHintCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hintCode, other.hintCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetHintContent()).compareTo(other.isSetHintContent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHintContent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hintContent, other.hintContent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Trace(");
    boolean first = true;

    sb.append("logId:");
    if (this.logId == null) {
      sb.append("null");
    } else {
      sb.append(this.logId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("caller:");
    if (this.caller == null) {
      sb.append("null");
    } else {
      sb.append(this.caller);
    }
    first = false;
    if (isSetSpanId()) {
      if (!first) sb.append(", ");
      sb.append("spanId:");
      if (this.spanId == null) {
        sb.append("null");
      } else {
        sb.append(this.spanId);
      }
      first = false;
    }
    if (isSetSrcMethod()) {
      if (!first) sb.append(", ");
      sb.append("srcMethod:");
      if (this.srcMethod == null) {
        sb.append("null");
      } else {
        sb.append(this.srcMethod);
      }
      first = false;
    }
    if (isSetHintCode()) {
      if (!first) sb.append(", ");
      sb.append("hintCode:");
      sb.append(this.hintCode);
      first = false;
    }
    if (isSetHintContent()) {
      if (!first) sb.append(", ");
      sb.append("hintContent:");
      if (this.hintContent == null) {
        sb.append("null");
      } else {
        sb.append(this.hintContent);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (logId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'logId' was not present! Struct: " + toString());
    }
    if (caller == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'caller' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TraceStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TraceStandardScheme getScheme() {
      return new TraceStandardScheme();
    }
  }

  private static class TraceStandardScheme extends org.apache.thrift.scheme.StandardScheme<Trace> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Trace struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LOG_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.logId = iprot.readString();
              struct.setLogIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CALLER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.caller = iprot.readString();
              struct.setCallerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SPAN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.spanId = iprot.readString();
              struct.setSpanIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SRC_METHOD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.srcMethod = iprot.readString();
              struct.setSrcMethodIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // HINT_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.hintCode = iprot.readI64();
              struct.setHintCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // HINT_CONTENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.hintContent = iprot.readString();
              struct.setHintContentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Trace struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.logId != null) {
        oprot.writeFieldBegin(LOG_ID_FIELD_DESC);
        oprot.writeString(struct.logId);
        oprot.writeFieldEnd();
      }
      if (struct.caller != null) {
        oprot.writeFieldBegin(CALLER_FIELD_DESC);
        oprot.writeString(struct.caller);
        oprot.writeFieldEnd();
      }
      if (struct.spanId != null) {
        if (struct.isSetSpanId()) {
          oprot.writeFieldBegin(SPAN_ID_FIELD_DESC);
          oprot.writeString(struct.spanId);
          oprot.writeFieldEnd();
        }
      }
      if (struct.srcMethod != null) {
        if (struct.isSetSrcMethod()) {
          oprot.writeFieldBegin(SRC_METHOD_FIELD_DESC);
          oprot.writeString(struct.srcMethod);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetHintCode()) {
        oprot.writeFieldBegin(HINT_CODE_FIELD_DESC);
        oprot.writeI64(struct.hintCode);
        oprot.writeFieldEnd();
      }
      if (struct.hintContent != null) {
        if (struct.isSetHintContent()) {
          oprot.writeFieldBegin(HINT_CONTENT_FIELD_DESC);
          oprot.writeString(struct.hintContent);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TraceTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TraceTupleScheme getScheme() {
      return new TraceTupleScheme();
    }
  }

  private static class TraceTupleScheme extends org.apache.thrift.scheme.TupleScheme<Trace> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Trace struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.logId);
      oprot.writeString(struct.caller);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSpanId()) {
        optionals.set(0);
      }
      if (struct.isSetSrcMethod()) {
        optionals.set(1);
      }
      if (struct.isSetHintCode()) {
        optionals.set(2);
      }
      if (struct.isSetHintContent()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetSpanId()) {
        oprot.writeString(struct.spanId);
      }
      if (struct.isSetSrcMethod()) {
        oprot.writeString(struct.srcMethod);
      }
      if (struct.isSetHintCode()) {
        oprot.writeI64(struct.hintCode);
      }
      if (struct.isSetHintContent()) {
        oprot.writeString(struct.hintContent);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Trace struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.logId = iprot.readString();
      struct.setLogIdIsSet(true);
      struct.caller = iprot.readString();
      struct.setCallerIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.spanId = iprot.readString();
        struct.setSpanIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.srcMethod = iprot.readString();
        struct.setSrcMethodIsSet(true);
      }
      if (incoming.get(2)) {
        struct.hintCode = iprot.readI64();
        struct.setHintCodeIsSet(true);
      }
      if (incoming.get(3)) {
        struct.hintContent = iprot.readString();
        struct.setHintContentIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

